### PR TITLE
Async DevRel Solution Pipelines

### PR DESCRIPTION
**Pull request by danistrebel**
What's changed, or what was fixed?

- running pipelines as async processes

**Fixes:** #issue

- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

### CODE REVIEW

**Comment by danistrebel** [comment]
trying full pipeline 
/gcbrun

**Review by laughingbiscuit — APPROVED** [review]

**Comment by danistrebel** [comment]
rebase upstream/main
/gcbrun

**Pull request merged**
