### PR TITLE
Feature/verify api key

### PR DESCRIPTION
**Pull request by markjkelly**
What's changed, or what was fixed?

- Added functionality to generate a Verify API Key policy and add to the Proxy PreFlow if the OAS provided specifies that ApiKeyAuth should be applied globally to all operations. API Keys as a query parameter or header are supported.

- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by laughingbiscuit** [comment]
the Dockerfile linting error isnt too descriptive (error 127) so will try to replicate locally

**Comment by laughingbiscuit** [comment]
resolved lint error

**Review by danistrebel — APPROVED** [review]
Thanks Mark. LGTM

**Pull request merged**
