### PR TITLE
BasePath Options for OAS Mock Generator

### PR DESCRIPTION
**Pull request by danistrebel**
What's changed, or what was fixed?

- allow for basepath overrides via servers or CLI option (basePath is no longer a TL entry in OAS 3.x)
- correct the run instructions in the README
- trivial fix for making SCRIPTPATH work with macOS

**Fixes:** #issue

- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by danistrebel** [comment]
@markjkelly please check out the small patches and let me know what you think

**Comment by laughingbiscuit** [comment]
lgtm but will hold on for marks comments

**Review by markjkelly — APPROVED** [review]
Looks good, thanks @danistrebel !

**Review by laughingbiscuit — APPROVED** [review]

**Pull request merged**
