### PR TITLE
feat: added support for multiple proxy split

### PR DESCRIPTION
**Pull request by anaik91**
## Description
What's changed, or what was fixed?

- Support for multiple proxy split / unification

## Issues Fixed
N/A
## Housekeeping
(please check all that apply [x], do not edit the text)
- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

## Full Repo Validation Required
(please check all that apply [x], do not edit the text)
- [ ] PR requires full pipeline run (Run for changes only by default).

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by OmidTahouri** [comment]
See build logs for environment errors

**Review by danistrebel — APPROVED** [review]

**Pull request merged**
