### PR TITLE
WIP Best practices hackathon

### PR DESCRIPTION
**Pull request by laughingbiscuit**
What's changed, or what was fixed?

-  added codelab for 300 level apigee hackathon

-   [x] I have run all the tests locally and they all pass.
-   [x] I have followed the relevant style guide for my changes.

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by laughingbiscuit** [comment]
@googlebot I consent.

**Comment by laughingbiscuit** [comment]
@seymen please review + merge

**Comment by seymen** [comment]
@laughingbiscuit apininja picture

**Comment by laughingbiscuit** [comment]
superceded by https://github.com/apigee/devrel/pull/63

**Pull request closed without merging**
