### PR TITLE
Fix what I assume is a typo in Sackmesser Deploy

### PR DESCRIPTION
**Pull request by velsietis**
## Description
Fixed typos in sackmesser's deploy.sh file

## Issues Fixed
The pom files have placeholders for a property called `baseuri` not `hosturi`, so I'm guessing that's what should be passed in.

 - [pom-hybrid.xml Line 58](https://github.com/apigee/devrel/blob/main/tools/apigee-sackmesser/cmd/deploy/pom-hybrid.xml#L58)
 - [pom-edge.xml Line 58](https://github.com/apigee/devrel/blob/main/tools/apigee-sackmesser/cmd/deploy/pom-edge.xml#L56)

Worth noting that we noticed this because we tried to run `sackmesser deploy` using git bash on Windows and got an error:
> MojoExecutionException: Unknown host null

Although we didn't get that error when running it in a Linux container.  I'm assuming that's because of some difference in Maven behaviour, i.e. on Linux it will just resolve `${baseuri}` from an environment variable so it doesn't matter it's passed in as a property

## Housekeeping
- [X] I have run all the tests locally and they all pass.
- [X] I have followed the relevant style guide for my changes.

## Full Repo Validation Required
- [ ] PR requires full pipeline run (Run for changes only by default).

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Review by danistrebel — APPROVED** [review]
Good spot. This is useful for making it work with OPDK

**Comment by danistrebel** [comment]
Hi @velsietis, Thanks a lot for the fix! The PR looks good but there's a few things our [contributing](https://github.com/apigee/devrel/blob/main/CONTRIBUTING.md) process requires.

Two simple steps that currently block the PR:
 - Accept the CLA. Please find more info [here](https://github.com/apigee/devrel/pull/595/checks?check_run_id=7998946703).
 - We require conventional commit messages to provide release notes and semantics. Could you please amend your commit (git --amend) and change the commit message to something like `fix: typo in Sackmesser Deploy`

**Comment by velsietis** [comment]
Thanks @danistrebel I've signed the CLA and updated the commit message (forgot I was naming the commit and not the PR as I just did it straight in GitHub and was feeling lazy to pull/amend/push...)

**Comment by danistrebel** [comment]
Awesome thanks a lot @velsietis

**Pull request merged**
