### PR TITLE
bump jenkins version

### PR DESCRIPTION
**Pull request by danistrebel**
## Description
What's changed, or what was fixed?

- Address Jenkins version incompatibility 

## Issues Fixed
- Fixes nightly

## Housekeeping
(please check all that apply [x], do not edit the text)
- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

## Full Repo Validation Required
(please check all that apply [x], do not edit the text)
- [ ] PR requires full pipeline run (Run for changes only by default).

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by adriens** [comment]
So it runs on a Jenkins ? :thinking:

**Comment by OmidTahouri** [comment]
> So it runs on a Jenkins ? 🤔

What does? This PR is to bump the version of Jenkins that is used in the [CI/CD Pipeline Reference](https://github.com/apigee/devrel/tree/main/references/cicd-pipeline) that can be used **if** you would like to deploy resources to Apigee using Jenkins. The DevRel build pipeline itself runs on [Google Cloud Build](https://cloud.google.com/build).

**Review by OmidTahouri — APPROVED** [review]

**Comment by adriens** [comment]
Thanks a lot @OmidTahouri  for the details, it's really very interesting to learn more about the pipeline :pray:

**Comment by danistrebel** [comment]
Looks like there's a version incompatibility between the jenkinsfilerunner, the newer Jenkins images and Jetty as described [here](https://github.com/jenkinsci/jenkinsfile-runner/issues/686).. I'll need to take a closer look than just blindly bumping the versions

**Pull request merged**
