### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kscheirer**
- Fixed links for petstore.json and expected.xml
- Can't find ./test/features/OASToAM.feature though

- [ ] I have run all the tests locally and they all pass.
- [ ] I have followed the relevant style guide for my changes.

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by danistrebel** [comment]
Thanks a lot for fixing the links @kscheirer! 
I added another commit to highlight that these files are just examples to illustrate the input and outputs.

**Review by danistrebel — APPROVED** [review]

**Review by laughingbiscuit — APPROVED** [review]

**Comment by kscheirer** [comment]
Thanks! Looking forward to using this repo.

**Pull request merged**
