### PR TITLE
Dutch Healthcare

### PR DESCRIPTION
**Pull request by laughingbiscuit**
Done:
- Pass through to sandbox
- Generate skeleton project structure
- Add shared flows
- Mediation example
- Pipeline using portable-proxy-deploy
- Increase test coverage

Notes:
- I have exposed all resources in one proxy as they have the same basepath

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by laughingbiscuit** [comment]
error handling might need to be tweaked as `/blah` returns 2xx

**Review by seymen — APPROVED** [review]

**Pull request merged**
