### PR TITLE
renamed referring proxy inside API products JSON

### PR DESCRIPTION
**Pull request by imanzarrabian**
## Description
What's changed, or what was fixed?

- fixes the name of the referenced proxy for during product creation

**Fixes:** #459

## Housekeeping
(please check all that apply [X], do not edit the text)
- [ ] I have run all the tests locally and they all pass.
- [ ] I have followed the relevant style guide for my changes.
- [ ] PR requires full pipeline run (Run for changes only by default).

**CC:** @apigee-devrel-reviewers

### CODE REVIEW

**Comment by danistrebel** [comment]
Thanks for the PR @imanzarrabian. The deployment utility by accident took the proxy name from the path `identity-facade` instead of the manifest file here https://github.com/apigee/devrel/blob/main/references/identity-facade/apiproxy/identity-facade-v1.xml#L13.

The deployment utility has been updated and should work again as expected. Also verified in the latest devrel nightly build.

**Comment by imanzarrabian** [comment]
thx a lot

**Comment by OmidTahouri** [comment]
@imanzarrabian Many thanks for the PR!
If you're now unblocked, please close this PR. Issue #459 can also be closed.

**Comment by danistrebel** [comment]
Closing as this is fixed in the tooling.

**Pull request closed without merging**
